modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="fraxy_timelapse"
version="${file.jarVersion}"
displayName="FraXy Timelapse"
authors="FraXyprojects"
description='''Server-side change detector and webhook trigger for Minecraft timelapse snapshots.'''

[[dependencies.fraxy_timelapse]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.fraxy_timelapse]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
